  build-arm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Compile Linux ARM64
        run: |
          gcc src/main.c -O3 -o umd-replace-linux-arm64

      - name: Compile for Android ARM64
        run: |
          $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
            src/main.c \
            -O3 \
            -o umd-replace-android-arm64

      - name: Upload ARM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-arm
          path: |
            umd-replace-linux-arm64
            umd-replace-android-arm64
